# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShareAMeal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShareAMeal

  target 'ShareAMealTests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

end
