"""empty message

Revision ID: e30aee234566
Revises: 
Create Date: 2019-12-16 21:03:25.564014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30aee234566'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mealDescription', sa.String(length=64), nullable=True),
    sa.Column('mealCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_mealCount'), 'meal', ['mealCount'], unique=False)
    op.create_index(op.f('ix_meal_mealDescription'), 'meal', ['mealDescription'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_mealDescription'), table_name='meal')
    op.drop_index(op.f('ix_meal_mealCount'), table_name='meal')
    op.drop_table('meal')
    # ### end Alembic commands ###
